big change

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -4,6 +4,12 @@ on:
   push:
     branches:
       - main
+env:
+  NAMESPACE: ${{ env.NAMESPACE }} # this is used as a prefix to resources in the helm chart.
+  TEST_NAMESPACE: getapp-f #  the namespace where you want to deploy the test environment
+
+  PROD_NAMESPACE: getapp-g #  the namespace where you want to deploy the production environment
+
 
 jobs: ##
   calculate_new_tag:
@@ -119,8 +125,7 @@ jobs: ##
           RELEASE_TAG: ${{ needs.calculate_new_tag.outputs.tag }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           PAT_ACCESS_TOKEN: ${{ secrets.PAT_TOKEN }}
-          NAMESPACE: "getapp-f"
-          replicaCount: "1"
+          NAMESPACE: ${{ env.NAMESPACE }}
         run: |
           #!/bin/bash
           set -x
@@ -156,11 +161,7 @@ jobs: ##
           sed -E -i "s,gitlabrelease":" .*,gitlabrelease":" ${GETAPP_RELEASE_TAG},g" helm-chart/values.yaml
 
           # getapp and getmap ##
-          sed -E -i "s,configmap":" .*,configmap":" ${NAMESPACE},g" helm-chart/values.yaml
-          sed -E -i "s,routePrefix":" .*,routePrefix":" ${NAMESPACE},g" helm-chart/values.yaml
-          sed -E -i "s,dbName":" .*,dbName":" ${NAMESPACE},g" helm-chart/values.yaml
-          sed -E -i "s,openshiftProjectName":" .*,openshiftProjectName":" ${NAMESPACE},g" helm-chart/values.yaml
-          sed -E -i "s,replicaCount":" .*,replicaCount":" ${replicaCount},g" helm-chart/values.yaml
+          sed -E -i "s,nameSpace":" .*,nameSpace":" ${NAMESPACE},g" helm-chart/values.yaml
           cat helm-chart/values.yaml
 
           # Copy installation scripts to root
@@ -244,7 +245,6 @@ jobs: ##
       # - get_agent_and_agent_ui
     name: Deploy and Test 
     env:
-      TEST_NAMESPACE: getapp-f #  the namespace where you want to deploy the test environment
       RELEASE_TAG: ${{ needs.calculate_new_tag.outputs.tag }}
     runs-on: ubuntu-latest
     steps:
@@ -267,70 +267,70 @@ jobs: ##
       - name: Deploy to test namespace ###
         env:
           RELEASE_TAG: ${{ needs.calculate_new_tag.outputs.tag }}
-          TEST_NAMESPACE: getapp-f
+          NAMESPACE: ${{ env.NAMESPACE }}
+          TEST_NAMESPACE: ${{ env.TEST_NAMESPACE }}
         run: |
           
           # test Deploy using Helm
           helm upgrade --install $TEST_NAMESPACE ./helm-chart \
             --namespace $TEST_NAMESPACE \
             --create-namespace   \
-            --set namespace.openshiftProjectName=$TEST_NAMESPACE \
+            --set nameSpace=$TEST_NAMESPACE \
             --dry-run
 
           # Deploy using Helm
           helm upgrade --install $TEST_NAMESPACE ./helm-chart \
             --namespace $TEST_NAMESPACE \
             --create-namespace   \
-            --set namespace.openshiftProjectName=$TEST_NAMESPACE \
+            --set nameSpace=$TEST_NAMESPACE \
 
   #         # Wait for deployment to be ready
   #         oc wait --for=condition=ready pod -l app=getapp --timeout=120s -n $TEST_NAMESPACE
 
-  #     - name: Run tests
-  #       env:
-  #         TEST_NAMESPACE: getapp-d
-  #       run: |
-  #         # Wait for route to be ready
-  #         oc wait --for=condition=ready route -l app=getapp -n $TEST_NAMESPACE --timeout=120s
+      - name: Run tests
+        env:
+          TEST_NAMESPACE: ${{ env.TEST_NAMESPACE }}
+        run: |
+          # # Wait for route to be ready
+          # oc wait --for=condition=ready route -l app=getapp -n $TEST_NAMESPACE --timeout=120s
           
-  #         # Get route URL (using oc command for OpenShift route)
-  #         ROUTE_URL=$(oc get route -l app=getapp -n $TEST_NAMESPACE -o jsonpath="{.items[0].spec.host}")
+          # Get route URL (using oc command for OpenShift route)
+          ROUTE_URL=$(oc get route -l app=getapp -n $TEST_NAMESPACE -o jsonpath="{.items[0].spec.host}")
           
-  #         # Basic health check using the route
-  #         curl -f https://$ROUTE_URL/docs || exit 1
+          # Basic health check using the route
+          curl -f https://$ROUTE_URL/docs || exit 1
         
-  #     - name: Deploy to production namespace
-  #       # if: success()
-  #       env:
-  #         RELEASE_TAG: ${{ needs.calculate_new_tag.outputs.tag }}
-  #         PROD_NAMESPACE: getapp-prod
-  #       run: |
-  #         # # Create production namespace if it doesn't exist
-  #         # oc create namespace $PROD_NAMESPACE --dry-run=client -o yaml | oc apply -f -
+      - name: Deploy to production namespace
+        # if: success()
+        env:
+          RELEASE_TAG: ${{ needs.calculate_new_tag.outputs.tag }}
+          PROD_NAMESPACE: ${{ env.PROD_NAMESPACE }}
+        run: |
           
-  #         # Deploy using Helm
-  #         helm upgrade --install getapp-f ./helm-chart \
-  #           --namespace $PROD_NAMESPACE \
-  #           --create-namespace   \
-  #           --set namespace.openshiftProjectName=$TEST_NAMESPACE \
-  #           --wait --timeout 5m 
-  #         helm upgrade --install getapp-f ./helm-chart \
-  #           --namespace $PROD_NAMESPACE \
-  #           --create-namespace   \
-  #           --set namespace.openshiftProjectName=$TEST_NAMESPACE \
-  #           --wait --timeout 5m 
-  #           --dry-run
-          
-  #         # Wait for deployment to be ready
-  #         oc wait --for=condition=ready pod -l app=getapp --timeout=300s -n $PROD_NAMESPACE
+          # Deploy using Helm
+          helm upgrade --install $PROD_NAMESPACE ./helm-chart \
+            --namespace $PROD_NAMESPACE \
+            --create-namespace   \
+            --set nameSpace=$PROD_NAMESPACE \
+            --wait --timeout 5m 
+            --dry-run
 
-  #     - name: Cleanup test deployment
-  #       if: always()
-  #       env:
-  #         TEST_NAMESPACE: getapp-f
-  #       run: |
-  #         # Clean up test namespace
-  #         helm uninstall getapp-f -n $TEST_NAMESPACE || true
+          helm upgrade --install $PROD_NAMESPACE ./helm-chart \
+            --namespace $PROD_NAMESPACE \
+            --create-namespace   \
+            --set nameSpace=$PROD_NAMESPACE \
+            --wait --timeout 5m 
+          
+          # # Wait for deployment to be ready
+          # oc wait --for=condition=ready pod -l app=getapp --timeout=300s -n $PROD_NAMESPACE
+
+      - name: Cleanup test deployment
+        if: always()
+        env:
+          TEST_NAMESPACE: ${{ env.TEST_NAMESPACE }}
+        run: |
+          # Clean up test namespace
+          helm uninstall $TEST_NAMESPACE -n $TEST_NAMESPACE || true
         
   # zip_images_and_chart_and_upload_to_azure:
   #   needs:
